name: Build A

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Build
        id: buildstep
        run: |
          echo "Running build..."
          echo "Something failed!" > error.txt
          exit 1
        continue-on-error: true

      - name: Send Error To Build B
        if: failure()
        run: |
          ERROR_MSG=$(cat error.txt | sed 's/"/\\"/g')

          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d "{\"event_type\":\"build_failed\",\"client_payload\":{\"error\":\"$ERROR_MSG\"}}"
