name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # -----------------------------
    # Setup .NET
    # -----------------------------
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # -----------------------------
    # Setup Java (Required for Maven)
    # -----------------------------
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # -----------------------------
    # Install Maven Dependencies
    # -----------------------------
    - name: Install Maven Dependencies
      id: mavenstep
      run: |
        mvn clean install -DskipTests 2> error.txt
      continue-on-error: true

    # -----------------------------
    # Restore .NET
    # -----------------------------
    - name: Restore dependencies
      id: restorestep
      run: dotnet restore 2>> error.txt
      continue-on-error: true

    # -----------------------------
    # Build .NET
    # -----------------------------
    - name: Build
      id: buildstep
      run: dotnet build --no-restore 2>> error.txt
      continue-on-error: true

    # -----------------------------
    # Test
    # -----------------------------
    - name: Test
      id: teststep
      run: dotnet test --no-build --verbosity normal 2>> error.txt
      continue-on-error: true

   # -----------------------------
    # Read Error File
    # -----------------------------
    - name: Read error file
      id: read_error
      run: |
        if [ -s error.txt ]; then
          ERROR=$(cat error.txt)
          echo "error_content<<EOF" >> $GITHUB_OUTPUT
          echo "$ERROR" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        else
          echo "error_content=No errors" >> $GITHUB_OUTPUT
        fi
    
  reusable_workflow_job:
    uses: 6268Abhishek/Crud_Web_API/.github/workflows/build-b.yml@main
    with:
      buildError: ${{ needs.build.outputs.error_output }}
      
