name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # -----------------------------
    # Setup .NET
    # -----------------------------
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # -----------------------------
    # Setup Java (Required for Maven)
    # -----------------------------
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # -----------------------------
    # Install Maven Dependencies
    # -----------------------------
    - name: Install Maven Dependencies
      id: mavenstep
      run: |
        mvn clean install -DskipTests 2> error.txt
      continue-on-error: true

    # -----------------------------
    # Restore .NET
    # -----------------------------
    - name: Restore dependencies
      id: restorestep
      run: dotnet restore 2>> error.txt
      continue-on-error: true

    # -----------------------------
    # Build .NET
    # -----------------------------
    - name: Build
      id: buildstep
      run: dotnet build --no-restore 2>> error.txt
      continue-on-error: true

    # -----------------------------
    # Test
    # -----------------------------
    - name: Test
      id: teststep
      run: dotnet test --no-build --verbosity normal 2>> error.txt
      continue-on-error: true

    # -----------------------------
    # Trigger Build B If Any Step Failed
    # -----------------------------
    - name: Trigger Build B on Failure
      if: |
        steps.mavenstep.outcome == 'failure' ||
        steps.restorestep.outcome == 'failure' ||
        steps.buildstep.outcome == 'failure' ||
        steps.teststep.outcome == 'failure'
      run: |
        ERROR_MSG=$(cat error.txt | sed 's/"/\\"/g')

        echo "Sending Error To Build B:"
        echo "$ERROR_MSG"

        curl -X POST \
        -H "Authorization: Bearer ${{ secrets.TEST_TOKEN }}" \
        -H "Accept: application/vnd.github+json" \
        https://api.github.com/repos/${{ github.repository }}/dispatches \ 
         -d "{\"event_type\":\"build_failed\"}"
